const colors = {
  light: {
    text: "#2F1B20",
    tint: "#7C9DD0",
    background: "#F2F2F2",
    foreground: "#2F1B20",
    card: "#FFFFFF",
    cardForeground: "#2F1B20",
    primary: "#7C9DD0",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF3FA",
    secondaryForeground: "#2F1B20",
    muted: "#F3F4F6",
    mutedForeground: "#9CA3AF",
    accent: "#F6F1AF",
    accentForeground: "#2F1B20",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#D1D5DB",
    wine: "#2F1B20",
    blue: "#7C9DD0",
    blueBg: "#EEF3FA",
    yellow: "#F6F1AF",
    yellowBorder: "#C8B840",
    statusOk: "#2D6A4F",
    statusOkBg: "#ECFDF5",
    statusWarning: "#B45309",
    statusWarningBg: "#FFFBEB",
    statusCritical: "#991B1B",
    statusCriticalBg: "#FEF2F2",
    statusExcellent: "#1D4ED8",
    statusExcellentBg: "#EFF6FF",
  },
  radius: 12,
};

export default colors;
